version: '3.3'
services:
  db:
    image: mysql:8.0
    container_name: db
    # Important command to allow legacy authentications for old versions
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: 1234
      DB_ROOT_PASSWORD: 1234
      DB_DATABASE: login
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - datadb:/var/lib/mysql
      - database:/docker-entrypoint-initdb.d
   # networks:
   #   - enve-net
   #  links:
   #  - app    
    deploy:
      resources:
        limits:
          memory: 1G
             
  app:
    container_name: app
    build: .
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: 1234
      DB_DATABASE: login
      DB_ROOT_PASSWORD: 1234
    ports:
      - "3000:3000"
    depends_on:
      - db    
   # networks:
   #   - enve-net
    links:
      - db    
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 1G
volumes:
  datadb: 
  database:
#networks:
#  enve-net:
